apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb
  namespace: ingress-demo
type: Opaque
data:
  db: bW9uZ29kYjovL2Nvc21vc2RhdGFzdG9yZTE6Y1NsY3NuTUNveGo5aFZ2VGw2Z3gzSXpXSkZMSFhDSFIxQUpMUHZOeHJ0YXo3M25ueU5hOVB3SUVpNmo4N0JaQVZITFhCamM1MzhuemNaVmNsSU1YZ2clM0QlM0RAY29zbW9zZGF0YXN0b3JlMS5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1L2NvbnRlbnRkYj9zc2w9dHJ1ZSZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUBjb3Ntb3NkYXRhc3RvcmUxQA==